
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.alex.compis;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int cadena = 14;
  public static final int texto = 7;
  public static final int identificadorC = 10;
  public static final int boleano = 13;
  public static final int coma = 15;
  public static final int numero = 32;
  public static final int publicos = 27;
  public static final int protegidos = 29;
  public static final int privados = 28;
  public static final int espacioBlanco = 5;
  public static final int finLinea = 4;
  public static final int propiedades = 22;
  public static final int incluir = 6;
  public static final int publicas = 24;
  public static final int protegidas = 26;
  public static final int nulo = 21;
  public static final int igual = 33;
  public static final int privadas = 25;
  public static final int metodos = 23;
  public static final int real = 12;
  public static final int EOF = 0;
  public static final int verdadero = 16;
  public static final int numeroR = 31;
  public static final int error = 1;
  public static final int comentario = 2;
  public static final int entero = 11;
  public static final int parentesisC = 20;
  public static final int identificadorVF = 18;
  public static final int clase = 8;
  public static final int dosPuntos = 30;
  public static final int parentesisA = 19;
  public static final int puntoComa = 3;
  public static final int falso = 17;
  public static final int extiende = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comentario",
  "puntoComa",
  "finLinea",
  "espacioBlanco",
  "incluir",
  "texto",
  "clase",
  "extiende",
  "identificadorC",
  "entero",
  "real",
  "boleano",
  "cadena",
  "coma",
  "verdadero",
  "falso",
  "identificadorVF",
  "parentesisA",
  "parentesisC",
  "nulo",
  "propiedades",
  "metodos",
  "publicas",
  "privadas",
  "protegidas",
  "publicos",
  "privados",
  "protegidos",
  "dosPuntos",
  "numeroR",
  "numero",
  "igual"
  };
}

